name: i501
dependencies:
  - python=3.10
  - pip
  - pip:
    - ipykernel
    - numpy
    - pandas
    - matplotlib
    - python-dotenv
    - requests
    - tqdm
    - networkx[default]
    - geopy 
    - folium
    - plotly==5.19.0
    - "jupyterlab>=3" "ipywidgets>=7.6"
    - scikit-learn